# Generated by Django 3.0.7 on 2020-06-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberid', models.IntegerField()),
                ('membername', models.CharField(max_length=30)),
                ('contribution', models.IntegerField()),
            ],
        ),
    ]
